version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: my_postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - "backend-network"
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data


